config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'

  get 'contacts/show'

  get 'contacts/new'

  get 'contacts/edit'

  get 'subscribers/index'

  devise_for :users

  root 'welcome#index'
  
  resources :skateboards do
  end
  resources :subscribers do
  end
  resources :contacts do
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/skateboard.rb
class Skateboard < ActiveRecord::Base
  has_attached_file :image,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
    @contact = Contact.new
  end
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create contact_params
    if @contact.save
    redirect_to root_path
    else 
      render :new
    end
  end
  private
  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/controllers/skateboards_controller.rb
class SkateboardsController < ApplicationController
    def index
    @skateboards = Skateboard.all
  end

  def show
    @skateboard = Skateboard.find params[:id]
  end

  def new
    @skateboard = Skateboard.new
  end

  def create
    @skateboard = Skateboard.create skateboard_params
    if @skateboard.save
    redirect_to skateboards_path
    else 
      render :new
    end
  end

  def edit
    @skateboard = Skateboard.find params[:id]
  end

  def update
    @skateboard = Skateboard.find params[:id]
    @skateboard.update_attributes skateboard_params
    redirect_to skateboards_path
  end

  def destroy
    @skateboard = Skateboard.find params[:id]
    @skateboard.delete
    redirect_to skateboards_path
  end

private
  def skateboard_params
    params.require(:skateboard).permit(:name, :retail_price, :size, :description, :image)
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscriber = Subscriber.new
  end
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.create subscriber_params
    if @subscriber.save
    redirect_to root_path
    else 
      render :new
    end
  end
  private
  def subscriber_params
    params.require(:subscriber).permit(:first_name, :last_name, :date_of_birth, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def login_links
    if user_signed_in?
      (link_to "Log Out", destroy_user_session_path, method: :delete)
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/skateboards_helper.rb
module SkateboardsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/edit.html.haml
%h1 Contacts#edit
%p Find me in app/views/contacts/edit.html.haml

app/views/contacts/index.html.haml
%h1 Contacts#index
%p Find me in app/views/contacts/index.html.haml

app/views/contacts/new.html.haml
%h1 Contacts#new
%p Find me in app/views/contacts/new.html.haml

app/views/contacts/show.html.haml
%h1 Contacts#show
%p Find me in app/views/contacts/show.html.haml

app/views/layouts/application.html.haml
!!!
/[if IE 9] <html class="lt-ie10" lang="en" >
%html.no-js{"data-useragent" => "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)", :lang => "en"}
  %head
    %link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans:400,700", :rel => "stylesheet", :type => "text/css"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title BlueIon
    %meta{:content => "Documentation and reference library for ZURB Foundation. JavaScript, CSS, components, grid and more.", :name => "description"}/
    %meta{:content => "ZURB, inc. ZURB network also includes zurb.com", :name => "author"}/
    %meta{:content => "ZURB, inc. Copyright (c) 2013", :name => "copyright"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags 
    = javascript_include_tag "vendor/modernizr"
  %body
    .row
      .small-12.columns.header
        .small-4.columns.blank
          &nbsp;
        .small-2.columns.subscribe
          = link_to "SUBSCRIBE",subscribers_path, class: "subscribe_link"
          %div.dot
        
        .small-4.columns.social_media

          %ul.social_media.button-group
            %li
              .small-1.columns.dots_line
                %div.dots
                %div.dots
                %div.dots
                %div.dots
              %a.button_facebook{:href => "https://www.facebook.com/"}
                %img{src:"/assets/facebook_image.jpg"}
              %a.button_rss{:href => "http://techcrunch.com/rssfeeds/"}
                %img{src:"/assets/rss_feed.jpg"}
              %a.button_twitter{:href => "https://twitter.com/"}
                %img{src:"/assets/twitter.jpg"} 
              %a.button_you_tube{:href => "https://www.youtube.com/"}
                %img{src:"/assets/you_tube.jpg"} 
        %h1
      .small-12.columns.navlinks
        %ul.right.button-group.nav
          %li
            %a.button{:href => "/#news"} - SK8T NEWS -
          %li
            %a.button{:href => "/#skateboarders"} - SKATEBOARDERS -
          %li
            %a.button{:href => "/#boards"} - BOARD DESIGN -
          %li
            %a.button{:href => "/#contact"} - CONTACT US -
    %p.notice= notice if notice
    %p.alert= alert if alert
    = yield
    %footer.row
      .small-12.columns
        %hr/
        .row
          .small-6.columns
            %p 
              &copy
          .small-6.columns.admin_login_link
            = link_to "Admin", user_session_path, class: "admin_login_link"
            = login_links


    %script{:src => "../assets/js/jquery.js"}
    %script{:src => "../assets/js/templates/foundation.js"}
    :javascript
      $(document).foundation();

      var doc = document.documentElement;
      doc.setAttribute('data-useragent', navigator.userAgent);

app/views/skateboards/_form.html.haml
= form_for [@skateboard], :html => { :multipart => true } do |f|
  - if @skateboard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skateboard.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @skateboard.errors.full_messages.each do |msg|
          %li= msg

  .input

    = f.text_field :name, :placeholder => "Name"
    = f.text_field :size, :placeholder => "Size"
    = f.text_field :description, :placeholder => "Description"
    = f.text_field :retail_price, :placeholder => "Retail Price"
    = f.label :image
    = f.file_field :image
    %br
    %br

    = f.submit "SUBMIT", class: "radius button left"

app/views/skateboards/edit.html.haml
= render 'form'
%br
%br
= link_to "Back", skateboards_path

app/views/skateboards/index.html.haml
.row.collapse
  - @skateboards.each do |skateboard|
    .small-4.small-offset-1.columns.skateboard_tile.end
      %ul.skateboard_info
        %h3.info
          = "#{skateboard.name}"
        = link_to skateboard_path(skateboard) do
          = image_tag skateboard.image
  

- if current_user
  = link_to "Add", new_skateboard_path

app/views/skateboards/new.html.haml
.row
  .small-12.column.forms
    %h3.forms
      Hello Admin!  
      %br
      So, you've got some new inventory?  Don't worry, this process is super easy- just grab your coffee and we'll get it knocked out of the park!

    = render 'form'
    %br
    %br
    %br
= link_to "Back", skateboards_path

app/views/skateboards/show.html.haml
.row
  .small-12.columns.skateboard_show
    %h3.name
      = @skateboard.name
    .small-6.columns.image
      .img.skateboard
        = image_tag @skateboard.image
    .small-6.stats
      %h4.stats
        Size:
        %br
          = @skateboard.size
        %br
        Description:
        %br
          = @skateboard.description
        %br
        Price:
        %br
          = @skateboard.retail_price

      -if current_user
        %br
        %br
          = link_to "Edit", edit_skateboard_path(@skateboard)
        %br
          = link_to "Remove From Inventory", skateboard_path(@skateboard), method: :delete

app/views/subscribers/_form.html.haml
= form_for [@subscriber] do |f|
  - if @subscriber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscriber.errors.count, "error")} prohibited this message from being sent:"
      %ul
        - @subscriber.errors.full_messages.each do |msg|
          %li= msg

  .input
    = f.text_field :first_name, :placeholder => "First Name"
    = f.text_field :last_name, :placeholder => "Last Name"
    = f.text_field :date_of_birth, :placeholder => "Birthday"
    = f.text_field :email, :placeholder => "Email Address"
    %br
    = f.submit "SUBMIT", class: "radius button left"

app/views/subscribers/index.html.haml
.row
  .small-12.column.forms
    %h3.forms
      Occasionally we send out emails to keep you updated on developments in the skateboard world, if you'd like to be put on our list please fill out the form below.  If you include your birthday we may just send you a special surprise that month!
    = render 'form'
    %br
    %br
    %br
    = link_to "Back", skateboards_path

app/views/welcome/index.html.haml
.row
  .small-12.columns
    %ul.example-orbit{"data-orbit" => ""}
      %li
        %img{:src => "../assets/top_image_1.jpg"}/
      %li
        %img{:src => "../assets/Slider_2.jpg"}/
      %li
        %img{:src => "../assets/Slider_3.jpg"}/
    .row#news
      .small-3.small-offset-1.columns.news_blocks
        %h4 
          Tony Hawk Foundation
          %br
          Raises Big Money At
          %br
          Celeb Fundraiser
        %p.date October 10, 2013
        %p.news_intro 
          It was just over 90 degrees in Los Angeles, but that didn't stop the throngs from coming out to celebrate the 10th Annual Tony Hawk's Stand Up For Skateparks Benefit Presented by SLS Hotel & Casino Las Vegas on Saturday at the Green Acres Estate in Beverly Hills.
        %div.read_more
          = link_to " [ READ MORE ]", "https://www.looktothestars.org/news/10903-tony-hawk-foundation-raises-big-money-at-celeb-fundraiser", class: "read_more"
      .small-3.small-offset-1.columns.news_blocks
        %h4 
          Rodney Mullen: Pop an ollie and innovate!
          %br
          (TED Talk)
        %p.date March 10, 2013
        %p.news_intro 
          The last thing Rodney Mullen, the godfather of street skating, wanted were competitive victories.  In this exuberant talk he shares his love of the open skateboarding community and how the unique environment plays in driving the creation of new tricks.
        %div.read_more
          = link_to "[ READ MORE ]", "https://www.ted.com/talks/rodney_mullen_pop_an_ollie_and_innovate", class: "read_more"
      .small-3.small-offset-1.columns.news_blocks

        %h4 
          Ray Barbee Talks
          %br
          'Ban This'
        %p.date October 4, 2013
        %p.news_intro 
          Since filming is in full swing for the Vans video Adventures With Chris has taken the opportunity to sit some of the team down to look behind the skating of some of their earlier parts. Today we sit down Ray Barbee, one of the smoothest guys to ever step on a skateboard and Chris' childhood idol...
        %div.read_more
          = link_to "[ READ MORE ]", "http://skateboarding.transworld.net/videos/ray-barbee-talks-ban-this/", class: "read_more"
    %br
    %br
    %br
    .row#skateboarders
    
    %table
      %tr
        %th#Lance
        %th#Rodney
        %th#Tommy{:rowspan => "2"} 
      %tr
        %td#Steve{:colspan => "2"} 
          

    %br
    .row#boards
      .small-12.columns.boards_display
        = link_to image_tag( '/assets/skateboards_all.png'), skateboards_path
      

        /user experience with individual links did not make sense with the  skateboards index I built, sorry!
        / %img.board{src:"/assets/Skateboard_1.png"}
        / %img.board{src:"/assets/Skateboard_2.jpg"}
        / %img.board{src:"/assets/Skateboard_3.jpg"}
        / %img.board{src:"/assets/Skateboard_4.jpg"}
        / %img.board{src:"/assets/Skateboard_5.jpg"}
        / %img.board{src:"/assets/Skateboard_6.jpg"}
        / %img.board{src:"/assets/Skateboard_7.jpg"}
        / %img.board{src:"/assets/Skateboard_8.jpg"}
        / %img.board{src:"/assets/Skateboard_9.jpg"}
        / %img.board{src:"/assets/Skateboard_10.jpg"}
    .row#contact
      .small-12.columns
        .panel
          %h4 Contact Us for More Information
          .row
            .small-12.columns.contact
              .small-6.columns.contact
                %p.contact_us 
                Love us? Hate us?  Either way, send us a comment and tell us what you think. 
                %br
                Have a question?  This is the form for that too!  Yep, we're saving you time left and right.  You're welcome.
              .small-6.columns.submit
                .contact_form
                = form_for [@contact], :html => { :multipart => true } do |f|
                  - if @contact.errors.any?
                    #error_explanation
                      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this item from being saved:"
                      %ul
                        - @contact.errors.full_messages.each do |msg|
                          %li= msg
                  .input.contact_form
                    = f.text_field :name, :placeholder => "Name"
                    = f.text_field :email, :placeholder => "Email Address"
                    = f.text_area :message, :placeholder => "Message"
                    %br
                  = f.submit "SUBMIT", class: "radius button right"

    

  